# vi:et:ts=2 sw=2 sts=2
image: pidgin/builder-debian:stretch
pipelines:
  default:
    - step:
        script:
          - set -ex
          - ./autogen.sh --enable-debug --enable-gtk-doc
          - make -s -j$(nproc)
          - make -s -j$(nproc) distcheck

